-- حذف السياسات الموجودة إن وجدت
DROP POLICY IF EXISTS "items_select_all" ON public.menu_items;
DROP POLICY IF EXISTS "items_write_all" ON public.menu_items;
DROP POLICY IF EXISTS "categories_select_all" ON public.menu_categories;
DROP POLICY IF EXISTS "categories_write_all" ON public.menu_categories;
DROP POLICY IF EXISTS "orders_select_all" ON public.orders;
DROP POLICY IF EXISTS "orders_insert_all" ON public.orders;
DROP POLICY IF EXISTS "orders_update_all" ON public.orders;
DROP POLICY IF EXISTS "audit_select_all" ON public.menu_audit_logs;
DROP POLICY IF EXISTS "audit_insert_all" ON public.menu_audit_logs;

-- إنشاء جدول العناصر (menu_items)
CREATE TABLE IF NOT EXISTS public.menu_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  price_sar DOUBLE PRECISION NOT NULL,
  quantity INTEGER,
  rating DOUBLE PRECISION,
  image TEXT,
  image_url TEXT,
  category TEXT NOT NULL,
  is_popular BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- إنشاء جدول الفئات (menu_categories)
CREATE TABLE IF NOT EXISTS public.menu_categories (
  name TEXT PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- إنشاء جدول الطلبات (orders)
CREATE TABLE IF NOT EXISTS public.orders (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  customer_name TEXT NOT NULL,
  customer_phone TEXT NOT NULL,
  customer_address TEXT NOT NULL,
  items JSONB NOT NULL,
  total_sar DOUBLE PRECISION NOT NULL,
  status TEXT DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- إنشاء جدول سجل التدقيق (menu_audit_logs)
CREATE TABLE IF NOT EXISTS public.menu_audit_logs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  action TEXT NOT NULL,
  payload JSONB,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- تمكين Row Level Security
ALTER TABLE public.menu_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.menu_audit_logs ENABLE ROW LEVEL SECURITY;

-- سياسات الوصول للعناصر
CREATE POLICY "items_select_all" ON public.menu_items FOR SELECT USING (true);
CREATE POLICY "items_write_all" ON public.menu_items FOR ALL USING (true) WITH CHECK (true);

-- سياسات الوصول للفئات
CREATE POLICY "categories_select_all" ON public.menu_categories FOR SELECT USING (true);
CREATE POLICY "categories_write_all" ON public.menu_categories FOR ALL USING (true) WITH CHECK (true);

-- سياسات الوصول للطلبات
CREATE POLICY "orders_select_all" ON public.orders FOR SELECT USING (true);
CREATE POLICY "orders_insert_all" ON public.orders FOR INSERT WITH CHECK (true);
CREATE POLICY "orders_update_all" ON public.orders FOR UPDATE USING (true);

-- سياسات الوصول لسجل التدقيق
CREATE POLICY "audit_select_all" ON public.menu_audit_logs FOR SELECT USING (true);
CREATE POLICY "audit_insert_all" ON public.menu_audit_logs FOR INSERT WITH CHECK (true);