// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ktnjwuyafrtlelasuhyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt0bmp3dXlhZnJ0bGVsYXN1aHl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQ4MDgsImV4cCI6MjA3MzEwMDgwOH0.WA83C3C-pKyNFnCC3Hm0GfUFEVgl4hi0DWsYQYDXYE4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});